services:
  weatherapp:
    build: .
    container_name: weatherapp_container
    ports:
      - "8080:8080"
    volumes:
      - ./weatherapp/src:/app/src
    env_file:
      - .env
    restart: unless-stopped
